[package]
name = "cesride"
version = "0.1.1"
edition = "2021"
description = "Implementation of Composable Event Streaming Representation (CESR)"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
