[package]
name = "keride"
version = "0.1.0"
edition = "2021"
description = "Implementation of Key Event Receipt Infrastructure"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
